database:
  # ประเภทฐานข้อมูล: "SQLITE" หรือ "MYSQL"
  type: "SQLITE"
  
  # การตั้งค่าสำหรับ SQLITE (ใช้ไฟล์)
  filename: "storage.db"
  
  # การตั้งค่าสำหรับ MYSQL (ใช้เซิร์ฟเวอร์)
  # mysql:
  #   host: "localhost"
  #   port: 3306
  #   database: "deathchest"
  #   username: "user"
  #   password: "password"

settings:
  despawn-timer: 200
  economy-provider: "VAULT"
  # 'currency-name' จะถูกใช้เมื่อ 'economy-provider' เป็น "COINS_ENGINE" เท่านั้น
  # currency-name: "coins"
  buyback-cost: 1
  allow-other-players-to-open: false # (ถ้า true = ใครก็เปิดได้, ถ้า false = เจ้าของเท่านั้น)
  hologram-y-offset: 1.5
  teleport-command-cooldown: 30
  hologram-lines:
    - "&f&l💀 §x§F§F§3§5§3§5§l%player%'s DEAD! &f&l💀"
    - "&7───────────────"
    - "&e📍 &f§x§F§E§E§C§3§6§l%coords%"
    - "&b✨ &f§x§2§9§F§F§0§0§l%xp% &fXP"
    - "&6⏳ &f§x§F§F§3§5§3§5§l%time% &fวินาที"
    - "&7───────────────"


messages:
  death: "§cคุณตาย! ของของคุณอยู่ในกล่องที่ตำแหน่ง: §f%coords% §c(XP: §f%xp%§c)"
  expired: "§cกล่องเก็บของของคุณหมดเวลา! §eคุณสามารถซื้อคืนได้ด้วยคำสั่ง §f/buyback"
  not_your_chest: "§cนี่ไม่ใช่กล่องศพของคุณ!"
  xp_restored: "§aคุณได้รับ XP คืน: %xp%"
  no_permission: "§cคุณไม่มียศพอที่จะใช้คำสั่งนี้!"
  no_chest_found: "§cไม่พบกล่องศพของคุณ"
  teleported: "§aวาร์ปไปยังกล่องศพของคุณ!"
  teleport-cooldown: "§cใจเย็น! ต้องรออีก %time% วินาทีก่อนจะวาร์ปได้"
  
  admin-no-player-found: "§cไม่พบผู้เล่นชื่อ %player% หรือผู้เล่นนี้ยังไม่เคยเข้าเซิร์ฟเวอร์"
  admin-no-chests-found: "§eผู้เล่น %player% ไม่มีกล่องศพที่กำลังใช้งานอยู่ หรือของใน Buyback"
  admin-teleported: "§aวาร์ปไปยังกล่องศพ!"
  admin-is-buyback: "§cนี่คือรายการใน Buyback ไม่สามารถวาร์ปได้"

logging:
  file:
    enable: true
    log-name: "DeathChestGUI.log"
  discord:
    enable: true
    webhook-url: "https://discord.com/api/webhooks/1431900997340495943/NQuOfa2hvKSnAUNwQKPNenLzfmWG9m25Qp_9xTORGlphVVfwF2mm45YFKTQVRGq6DPbL"
    username: "DeathChest Logger"